### ISSUE TITLE
Idea: Reconfigure needs a wear-off message, or should never wear off

### ISSUE THREAD

**Issue by mikeclemson** [TempusMUD/Tempuscode#116]
Jim      (Nov  1) [30013] reconfigure shouldn't "wear off" it should be more of a gradual repair system to reconfigure back to orignal form or you should need an overhaul to get you back to normal

Add a wear off message to reconfigure explaining why the reconfiguration has ended.  Alternatively, implement Jim's request so that an overhaul or similar process is required.

**Comment by dlowe-net** [comment]
Made the reconfigure affect permanent so that an overhaul or reboot is needed.
