### ISSUE TITLE
Strike uses the wrong weapon sometimes

### ISSUE THREAD

**Issue by mikeclemson** [TempusMUD/Tempuscode#479]
In act.offensive.c, strike can use either wielded or hand weapons, but will always set weapon to the wielded weapon. It also doesn't check for off-hand weapons. It should check for wield, second wield, hand, and for each, set weap to that object.

**Comment by dlowe-net** [comment]
Looking at the description, it didn't make sense for this to work with off-hand weapons. The hand weapon did need to be assigned, though.
