### ISSUE TITLE
Can we get a dump of non-player data?

### ISSUE THREAD

**Issue by andrewnhem** [TempusMUD/Tempuscode#516]
@origintempus : @nucleardreamer and I are trying to containerize TempusMUD and run it on a Raspberry Pi as a side project. We were wondering if we could get a copy of the game data minus sensitive player stuff. Is this possible?

I realize writing an issue is a weird way to ask this, but I wasn't sure who was still maintaining or has the archives to TempusMUD :p

**Comment by origintempus** [comment]
What do you mean by game data? The Github repository has all of the source plus a sample world library (if that's what you mean). If you can get Tempus to run on a clean version of Linux let me know how you overcame the issues with PostgreSQL and the legacy Tempus config.

**Comment by andrewnhem** [comment]
@origintempus Ah right on. Wasn't sure if the sample world library was just the original CircleMUD stuff.

> If you can get Tempus to run on a clean version of Linux let me know how you overcame the issues with PostgreSQL and the legacy Tempus config.

For sure. Will report in once we seem some more wins.

**Comment by andrewnhem** [comment]
@origintempus Pretty fun so far. We got a containerized version working and connecting locally. Now we're trying to run it on a platform called balena to simplify the networking requirements and run it headless on a Raspberry Pi4.

I have a friend looking into your request about a clean Linux setup.

Any chance we can get the actual TempusMUD world and mob data? I just want to run the game privately for some friends who've never played.

**Comment by origintempus** [comment]
No on the world and mob files. Not mine to give.

**Comment by andrewnhem** [comment]
@origintempus That's fair! Thought we'd ask!

So far we've docker-ized it using debian:jessie and postgres 14.x. I saw the note on the news in-game saying you prefer Ubuntu 21. Might try that soon.

**Comment by dlowe-net** [comment]
To build on a modern system, you'll want https://github.com/dlowe-net/Tempuscode/commit/c9d11b277dab79b491c2fd2d1fc321992b1f5d9e to fix the postgres linking, and https://github.com/dlowe-net/Tempuscode/commit/a0ac0488c418b18f770960ec13a52ddb0d57f853 to remove multiple references to the voice table.
